# Generated by Django 4.2 on 2024-01-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Graffiti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinCommunitySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Phone_number', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
